/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ventanas;

/**
 *
 * @author bcastrof
 */
public class Administracion extends javax.swing.JFrame {

    /**
     * Creates new form Administracion
     */
    public Administracion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bCentros1 = new javax.swing.JButton();
        bTrabajadores1 = new javax.swing.JButton();
        bVehiculos1 = new javax.swing.JButton();
        bPartes1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administración");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bCentros1.setText("Centros");
        bCentros1.setMaximumSize(new java.awt.Dimension(97, 23));
        bCentros1.setMinimumSize(new java.awt.Dimension(97, 23));
        bCentros1.setPreferredSize(new java.awt.Dimension(97, 23));
        getContentPane().add(bCentros1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, -1, 30));

        bTrabajadores1.setText("Trabajadores");
        getContentPane().add(bTrabajadores1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, -1, 30));

        bVehiculos1.setText("Vehiculos");
        bVehiculos1.setToolTipText("");
        bVehiculos1.setPreferredSize(new java.awt.Dimension(97, 23));
        getContentPane().add(bVehiculos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, -1, 30));

        bPartes1.setText("Partes");
        bPartes1.setPreferredSize(new java.awt.Dimension(97, 23));
        getContentPane().add(bPartes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, -1, 30));

        jLabel5.setText("Gestión");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel6.setText("Gestión");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        jLabel7.setText("Gestión");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, -1));

        jLabel8.setText("Gestión");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administracion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCentros1;
    private javax.swing.JButton bPartes1;
    private javax.swing.JButton bTrabajadores1;
    private javax.swing.JButton bVehiculos1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
