--VISUALIZACION DE TODOS LOS CENTROS PAQUETES
CREATE OR REPLACE PACKAGE CONSULTACENTROS
AS 
PROCEDURE CENTROS (C OUT SYS_REFCURSOR);
END CONSULTACENTROS;

CREATE OR REPLACE PACKAGE BODY CONSULTACENTROS AS 
 PROCEDURE CENTROS(C OUT SYS_REFCURSOR) AS
 BEGIN 
  OPEN C FOR
SELECT ID, NOMBRE,  CALLE, NUMERO, CIUDAD, CODIGOPOSTAL, PROVINCIA, TELEFONO FROM CENTROS;
 END CENTROS;
END CONSULTACENTROS;


--VISUALIZACION DE TODOS LOS CENTROS Y DE UN CENTRO EN CONCRETO
DROP PACKAGE COMPLEJOS;
CREATE OR REPLACE PACKAGE COMPLEJOS
 
AS 
 
PROCEDURE CONSULTACENTROS (C OUT SYS_REFCURSOR);
 
PROCEDURE CONSULTACENTRO (BUSCAR IN CENTROS.NOMBRE%type, C OUT SYS_REFCURSOR);
 
END COMPLEJOS;
 


create or replace PACKAGE BODY COMPLEJOS AS 
 PROCEDURE CONSULTACENTROS(C OUT SYS_REFCURSOR) 
 AS
 BEGIN 
  OPEN C FOR
SELECT ID, NOMBRE,  CALLE, NUMERO, CIUDAD, CODIGOPOSTAL, PROVINCIA, TELEFONO 
FROM CENTROS
ORDER BY ID;
   
  END CONSULTACENTROS;

  PROCEDURE CONSULTACENTRO (BUSCAR IN CENTROS.NOMBRE%type, C OUT SYS_REFCURSOR)
AS
 BEGIN 
open c for
SELECT ID, NOMBRE, CALLE, NUMERO, CIUDAD, CODIGOPOSTAL, PROVINCIA, TELEFONO 
FROM centros 
WHERE UPPER(NOMBRE)=BUSCAR OR LOWER(NOMBRE)=BUSCAR
order by ID ;
EXCEPTION 
    WHEN NO_DATA_FOUND THEN 
      RAISE_APPLICATION_ERROR(-20004,'No se ha encontrado el centro');
    WHEN TOO_MANY_ROWS THEN 
      RAISE_APPLICATION_ERROR(-20002,'Ha ocurrido un error'); 
    WHEN OTHERS THEN 
      RAISE_APPLICATION_ERROR(-20002,'Ha ocurrido un error'); 

END CONSULTACENTRO;
END COMPLEJOS;

--LISTADO DE EMPLEADOS
DROP PROCEDURE LISTADOEMPLEADOS;	
	
CREATE OR REPLACE PROCEDURE LISTADOEMPLEADOS
(IDN IN VARCHAR2, C OUT SYS_REFCURSOR)
AS
BEGIN
OPEN C FOR
SELECT * FROM TRABAJADORES WHERE CENTROS_ID=IDN;
CLOSE C;
END LISTADOEMPLEADOS;

--VER UN EMPLEADO
DROP PROCEDURE EMPLEADO;

CREATE OR REPLACE PROCEDURE EMPLEADO
(IDN IN VARCHAR 2, C OUT SYS_REFCURSOR)
AS 
BEGIN
OPEN C FOR
SELECT * FROM TRABAJADORES WHERE ID=IDN;
CLOSE C;
END EMPLEADO;